name = "pretty_diff"
version = "1.0.1"

description = "âš–ï¸ Pretty diffing of Gleam values"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "pretty_diff" }

[dependencies]
gleam_stdlib = ">= 0.50.0 and < 2.0.0"
glam = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.1.6 and < 2.0.0"
